create table public.brewing_method
(
    id          integer generated by default as identity
        constraint brewing_method_pk
            primary key,
    name        varchar(255) not null,
    description text         not null
);

alter table public.brewing_method
    owner to postgres;

create table public.country
(
    id   integer generated by default as identity
        constraint country_pk
            primary key,
    name varchar(255) not null
);

alter table public.country
    owner to postgres;

create table public.processing_method
(
    id   integer generated by default as identity
        constraint processing_method_pk
            primary key,
    name varchar(255) not null
);

alter table public.processing_method
    owner to postgres;

create table public.region
(
    id         integer generated by default as identity
        constraint region_pk
            primary key,
    name       varchar(255) not null,
    country_id integer      not null
        constraint region_country
            references public.country
);

alter table public.region
    owner to postgres;

create index idx_region_country_id
    on public.region (country_id);

create table public.roastery
(
    id   integer generated by default as identity
        constraint roastery_pk
            primary key,
    name varchar(255) not null
);

alter table public.roastery
    owner to postgres;

create table public.variety
(
    id   integer generated by default as identity
        constraint variety_pk
            primary key,
    name varchar(255) not null
);

alter table public.variety
    owner to postgres;

create table public.app_user
(
    id              integer generated by default as identity
        constraint app_user_pk
            primary key,
    email           varchar(255)                        not null
        unique,
    password_hash   varchar(255)                        not null,
    login           varchar(50)                         not null
        unique,
    role            varchar(50)                         not null,
    activity_points integer   default 0                 not null,
    label           varchar(255),
    is_blocked      boolean   default false             not null,
    created_at      timestamp default CURRENT_TIMESTAMP not null,
    password_hint   varchar(255)
);

alter table public.app_user
    owner to postgres;

create table public.cupping_session
(
    id           integer generated by default as identity
        constraint cupping_session_pk
            primary key,
    name         varchar(255)                        not null,
    description  text,
    session_date timestamp,
    created_at   timestamp default CURRENT_TIMESTAMP not null,
    user_id      integer                             not null
        constraint cupping_session_user
            references public.app_user
);

alter table public.cupping_session
    owner to postgres;

create index idx_cupping_session_user_id
    on public.cupping_session (user_id);

create index idx_cupping_session_name_search
    on public.cupping_session using gin (brewbase_search_text(name::text) public.gin_trgm_ops);

create table public.follow
(
    follower_id integer   not null
        constraint follower_user
            references public.app_user,
    followed_id integer   not null
        constraint followed_user
            references public.app_user,
    created_at  timestamp not null,
    constraint follow_pk
        primary key (follower_id, followed_id)
);

alter table public.follow
    owner to postgres;

create index idx_follow_followed_id
    on public.follow (followed_id);

create table public.notification
(
    id         integer generated by default as identity
        constraint notification_pk
            primary key,
    user_id    integer               not null
        constraint notification_user
            references public.app_user,
    content    text                  not null,
    created_at timestamp             not null,
    is_read    boolean default false not null
);

alter table public.notification
    owner to postgres;

create index idx_notification_user_id
    on public.notification (user_id);

create table public.quick_note
(
    id         integer generated by default as identity
        constraint quick_note_pk
            primary key,
    content    text      not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id    integer   not null
        constraint quick_notes_user
            references public.app_user
);

alter table public.quick_note
    owner to postgres;

create index idx_quick_note_user_id
    on public.quick_note (user_id);

create index idx_quick_note_content_search
    on public.quick_note using gin (brewbase_search_text(content) public.gin_trgm_ops);

create table public.user_preference
(
    id                    integer generated by default as identity
        constraint user_preference_pk
            primary key,
    preferred_roast_level varchar(255)          not null,
    favorite_notes        text                  not null,
    quiz_completed        boolean               not null,
    user_id               integer               not null
        constraint user_preferences_user
            references public.app_user,
    experience_level      varchar(50),
    preferred_acidity     varchar(50),
    preferred_body        varchar(50),
    recommendation_style  varchar(100),
    allow_exploration     boolean default false not null
);

alter table public.user_preference
    owner to postgres;

create index idx_user_preference_user_id
    on public.user_preference (user_id);

create table public.user_ranking
(
    id                             integer generated by default as identity
        constraint user_ranking_pk
            primary key,
    refreshed_at                   timestamp         not null,
    activity_score                 integer           not null,
    user_id                        integer           not null
        constraint ranking_user_user
            references public.app_user,
    position                       integer default 0 not null,
    public_recipe_count            integer default 0 not null,
    coffee_rating_count            integer default 0 not null,
    recipe_rating_count            integer default 0 not null,
    cupping_session_count          integer default 0 not null,
    followers_count                integer default 0 not null,
    received_recipe_favorite_count integer default 0 not null,
    published_article_count        integer default 0 not null
);

alter table public.user_ranking
    owner to postgres;

create index idx_user_ranking_user_id
    on public.user_ranking (user_id);

create index idx_app_user_login_search
    on public.app_user using gin (brewbase_search_text(login::text) public.gin_trgm_ops);

create index idx_app_user_label_search
    on public.app_user using gin (brewbase_search_text(COALESCE(label, ''::character varying)::text)
    public.gin_trgm_ops);

create table public.flavor_profile
(
    id   serial
        primary key,
    name varchar(100) not null
        unique
);

alter table public.flavor_profile
    owner to postgres;

create table public.user_preference_flavor_profile
(
    user_preference_id integer not null
        constraint fk_user_preference_flavor_profile_preference
            references public.user_preference
            on delete cascade,
    flavor_profile_id  integer not null
        constraint fk_user_preference_flavor_profile_flavor
            references public.flavor_profile
            on delete cascade,
    primary key (user_preference_id, flavor_profile_id)
);

alter table public.user_preference_flavor_profile
    owner to postgres;

create table public.user_preference_brewing_method
(
    user_preference_id integer not null
        constraint fk_upbm_preference
            references public.user_preference
            on delete cascade,
    brewing_method_id  integer not null
        constraint fk_upbm_method
            references public.brewing_method
            on delete cascade,
    primary key (user_preference_id, brewing_method_id)
);

alter table public.user_preference_brewing_method
    owner to postgres;

create table public.user_preference_region
(
    user_preference_id integer not null
        constraint fk_upr_preference
            references public.user_preference
            on delete cascade,
    region_id          integer not null
        constraint fk_upr_region
            references public.region
            on delete cascade,
    primary key (user_preference_id, region_id)
);

alter table public.user_preference_region
    owner to postgres;

create table public.acidity
(
    id          integer generated by default as identity
        constraint acidity_pk
            primary key,
    name        varchar(255) not null
        unique,
    description text
);

alter table public.acidity
    owner to postgres;

create table public.body
(
    id          integer generated by default as identity
        constraint body_pk
            primary key,
    name        varchar(255) not null
        unique,
    description text
);

alter table public.body
    owner to postgres;

create table public.coffee
(
    id                   integer generated by default as identity
        constraint coffee_pk
            primary key,
    name                 varchar(255) not null,
    roastery_id          integer      not null
        constraint coffee_roasteries
            references public.roastery,
    region_id            integer      not null
        constraint coffee_regions
            references public.region,
    variety_id           integer
        constraint coffee_varieties
            references public.variety,
    processing_method_id integer
        constraint coffee_processing_methods
            references public.processing_method,
    created_by_user_id   integer      not null
        constraint coffee_user
            references public.app_user,
    is_verified          boolean      not null,
    acidity_id           integer
        constraint coffee_acidity
            references public.acidity,
    body_id              integer
        constraint coffee_body
            references public.body
);

alter table public.coffee
    owner to postgres;

create table public.article
(
    id                   integer generated by default as identity
        constraint article_pk
            primary key,
    title                varchar(255)                                     not null,
    content              text                                             not null,
    status               varchar(50)                                      not null,
    created_at           timestamp                                        not null,
    updated_at           timestamp                                        not null,
    published_at         timestamp,
    moderated_by_user_id integer
        constraint article_moderator_user
            references public.app_user,
    moderated_at         timestamp,
    moderation_comment   text,
    user_id              integer                                          not null
        constraint article_user
            references public.app_user,
    module               varchar(50) default 'general'::character varying not null,
    coffee_id            integer
        constraint article_coffee_fk
            references public.coffee
);

alter table public.article
    owner to postgres;

create index idx_article_user_id
    on public.article (user_id);

create index idx_article_moderated_by_user_id
    on public.article (moderated_by_user_id);

create index idx_article_coffee_id
    on public.article (coffee_id);

create unique index uq_article_coffee_wiki
    on public.article (coffee_id)
    where (((module)::text = 'coffee'::text) AND ((status)::text = 'Approved'::text) AND (coffee_id IS NOT NULL));

create index idx_article_title_search
    on public.article using gin (brewbase_search_text(title::text) public.gin_trgm_ops);

create index idx_article_content_search
    on public.article using gin (brewbase_search_text(content) public.gin_trgm_ops);

create index idx_coffee_created_by_user_id
    on public.coffee (created_by_user_id);

create index idx_coffee_region_id
    on public.coffee (region_id);

create index idx_coffee_roastery_id
    on public.coffee (roastery_id);

create index idx_coffee_processing_method_id
    on public.coffee (processing_method_id);

create index idx_coffee_variety_id
    on public.coffee (variety_id);

create index idx_coffee_name_search
    on public.coffee using gin (brewbase_search_text(name::text) public.gin_trgm_ops);

create index idx_coffee_acidity_id
    on public.coffee (acidity_id);

create index idx_coffee_body_id
    on public.coffee (body_id);

create table public.coffee_ranking
(
    id                integer generated by default as identity
        constraint coffee_ranking_pk
            primary key,
    refreshed_at      timestamp                  not null,
    rating_count      integer                    not null,
    recipe_used_count integer                    not null,
    like_count        integer                    not null,
    coffee_id         integer                    not null
        constraint ranking_coffee_coffee
            references public.coffee,
    position          integer          default 0 not null,
    average_rating    double precision default 0 not null,
    ranking_score     double precision default 0 not null
);

alter table public.coffee_ranking
    owner to postgres;

create index idx_coffee_ranking_coffee_id
    on public.coffee_ranking (coffee_id);

create table public.coffee_rating
(
    id         integer generated by default as identity
        constraint coffee_rating_pk
            primary key,
    value      integer   not null
        constraint chk_coffee_rating_value
            check ((value >= 1) AND (value <= 5)),
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id    integer   not null
        constraint rating_coffee_user
            references public.app_user,
    coffee_id  integer   not null
        constraint rating_coffee_coffee
            references public.coffee
);

alter table public.coffee_rating
    owner to postgres;

create index idx_coffee_rating_user_id
    on public.coffee_rating (user_id);

create index idx_coffee_rating_coffee_id
    on public.coffee_rating (coffee_id);

create table public.cupping_session_coffee
(
    id                   integer generated by default as identity
        constraint cupping_session_coffee_pk
            primary key,
    notes                text,
    aroma_score          integer,
    sweetness_score      integer,
    acidity_score        integer,
    body_score           integer,
    flavor_profile_notes text,
    overall_score        integer,
    created_at           timestamp default CURRENT_TIMESTAMP not null,
    coffee_id            integer
        constraint cupping_session_coffee_coffee
            references public.coffee,
    cupping_session_id   integer                             not null
        constraint cupping_session_coffee_session
            references public.cupping_session,
    custom_coffee_name   varchar(255),
    constraint uq_session_coffee
        unique (cupping_session_id, coffee_id)
);

alter table public.cupping_session_coffee
    owner to postgres;

create index idx_cupping_session_coffee_coffee_id
    on public.cupping_session_coffee (coffee_id);

create index idx_cupping_session_coffee_cupping_session_id
    on public.cupping_session_coffee (cupping_session_id);

create table public.recipe
(
    id                 integer generated by default as identity
        constraint recipe_pk
            primary key,
    title              varchar(255)                        not null,
    parameters         jsonb                               not null,
    steps              text                                not null,
    is_public          boolean                             not null,
    user_id            integer                             not null
        constraint recipes_user
            references public.app_user,
    brewing_method_id  integer
        constraint recipes_brewing_methods
            references public.brewing_method,
    coffee_id          integer
        constraint recipes_coffee
            references public.coffee,
    created_at         timestamp default CURRENT_TIMESTAMP not null,
    moderation_comment text
);

alter table public.recipe
    owner to postgres;

create index idx_recipe_user_id
    on public.recipe (user_id);

create index idx_recipe_coffee_id
    on public.recipe (coffee_id);

create index idx_recipe_brewing_method_id
    on public.recipe (brewing_method_id);

create index idx_recipe_title_search
    on public.recipe using gin (brewbase_search_text(title::text) public.gin_trgm_ops);

create table public.recipe_ranking
(
    id             integer generated by default as identity
        constraint recipe_ranking_pk
            primary key,
    refreshed_at   timestamp                  not null,
    rating_count   integer                    not null,
    save_count     integer                    not null,
    recipe_id      integer                    not null
        constraint ranking_recipe_recipe
            references public.recipe,
    position       integer          default 0 not null,
    average_rating double precision default 0 not null,
    ranking_score  double precision default 0 not null
);

alter table public.recipe_ranking
    owner to postgres;

create index idx_recipe_ranking_recipe_id
    on public.recipe_ranking (recipe_id);

create table public.recipe_rating
(
    id         integer generated by default as identity
        constraint recipe_rating_pk
            primary key,
    value      integer   not null
        constraint chk_recipe_rating_value
            check ((value >= 1) AND (value <= 5)),
    created_at timestamp not null,
    updated_at timestamp not null,
    user_id    integer   not null
        constraint rating_recipe_user
            references public.app_user,
    recipe_id  integer   not null
        constraint rating_recipe_recipes
            references public.recipe
);

alter table public.recipe_rating
    owner to postgres;

create index idx_recipe_rating_user_id
    on public.recipe_rating (user_id);

create index idx_recipe_rating_recipe_id
    on public.recipe_rating (recipe_id);

create table public.recommendations
(
    id                 integer generated by default as identity
        constraint recommendations_pk
            primary key,
    feedback           boolean     not null,
    score              integer     not null,
    algorithm          varchar(30) not null,
    generated_at       timestamp   not null,
    feedback_at        timestamp,
    source             text        not null,
    coffee_id          integer
        constraint recommendations_coffee
            references public.coffee,
    recipe_id          integer
        constraint recommendations_recipe
            references public.recipe,
    user_id            integer     not null
        constraint recommendations_user
            references public.app_user,
    user_preference_id integer
        constraint recommendations_user_preferences
            references public.user_preference,
    coffee_ranking_id  integer
        constraint recommendations_ranking_coffee
            references public.coffee_ranking,
    constraint chk_recommendation_target
        check (((coffee_id IS NOT NULL) AND (recipe_id IS NULL)) OR ((coffee_id IS NULL) AND (recipe_id IS NOT NULL)))
);

alter table public.recommendations
    owner to postgres;

create index idx_recommendations_user_id
    on public.recommendations (user_id);

create index idx_recommendations_coffee_id
    on public.recommendations (coffee_id);

create index idx_recommendations_recipe_id
    on public.recommendations (recipe_id);

create index idx_recommendations_user_preference_id
    on public.recommendations (user_preference_id);

create index idx_recommendations_coffee_ranking_id
    on public.recommendations (coffee_ranking_id);

create table public.user_recipe_favorite
(
    user_id    integer                             not null
        constraint user_recipe_favorite_user
            references public.app_user,
    recipe_id  integer                             not null
        constraint user_recipe_favorite_recipe
            references public.recipe,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    constraint user_recipe_favorite_pk
        primary key (user_id, recipe_id)
);

alter table public.user_recipe_favorite
    owner to postgres;

create index idx_user_recipe_favorite_recipe_id
    on public.user_recipe_favorite (recipe_id);

create table public.report
(
    id                  integer generated by default as identity
        constraint report_pk
            primary key,
    reason              text                                not null,
    created_at          timestamp default CURRENT_TIMESTAMP not null,
    article_id          integer                             not null
        constraint report_article_fk
            references public.article,
    reported_by_user_id integer                             not null
        constraint report_user_fk
            references public.app_user
);

alter table public.report
    owner to postgres;

create index idx_report_article_id
    on public.report (article_id);

create index idx_report_reported_by_user_id
    on public.report (reported_by_user_id);

create table public.user_coffee_favorite
(
    user_id    integer                             not null
        constraint user_coffee_favorite_user
            references public.app_user,
    coffee_id  integer                             not null
        constraint user_coffee_favorite_coffee
            references public.coffee,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    constraint user_coffee_favorite_pk
        primary key (user_id, coffee_id)
);

alter table public.user_coffee_favorite
    owner to postgres;

create index idx_user_coffee_favorite_coffee_id
    on public.user_coffee_favorite (coffee_id);

create table public.coffee_flavor_profile
(
    coffee_id         integer not null
        constraint fk_coffee_flavor_profile_coffee
            references public.coffee
            on delete cascade,
    flavor_profile_id integer not null
        constraint fk_coffee_flavor_profile_flavor_profile
            references public.flavor_profile
            on delete cascade,
    constraint pk_coffee_flavor_profile
        primary key (coffee_id, flavor_profile_id)
);

alter table public.coffee_flavor_profile
    owner to postgres;

