-- database schema generated from ERD
-- Last modification date: 2026-05-31 (global search infrastructure)

-- =====================
-- Tables
-- =====================

-- Table: article
CREATE TABLE article (
                         id int GENERATED BY DEFAULT AS IDENTITY,
                         title varchar(255)  NOT NULL,
                         content text  NOT NULL,
                         status varchar(50)  NOT NULL,
                         module varchar(50)  NOT NULL DEFAULT 'general',
                         created_at timestamp  NOT NULL,
                         updated_at timestamp  NOT NULL,
                         published_at timestamp  NULL,
                         moderated_by_user_id int  NULL,
                         moderated_at timestamp  NULL,
                         moderation_comment text  NULL,
                         user_id int  NOT NULL,
                         coffee_id int  NULL,
                         CONSTRAINT article_pk PRIMARY KEY (id)
);

-- Table: brewing_method
CREATE TABLE brewing_method (
                                id int GENERATED BY DEFAULT AS IDENTITY,
                                name varchar(255)  NOT NULL,
                                description text  NOT NULL,
                                CONSTRAINT brewing_method_pk PRIMARY KEY (id)
);

-- Table: coffee
CREATE TABLE coffee (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        name varchar(255)  NOT NULL,
                        roastery_id int  NOT NULL,
                        region_id int  NOT NULL,
                        variety_id int  NULL,
                        processing_method_id int  NULL,
                        created_by_user_id int  NOT NULL,
                        is_verified boolean  NOT NULL,
                        CONSTRAINT coffee_pk PRIMARY KEY (id)
);

-- Table: coffee_ranking
CREATE TABLE coffee_ranking (
                                id int GENERATED BY DEFAULT AS IDENTITY,
                                refreshed_at timestamp  NOT NULL,
                                rating_count int  NOT NULL,
                                recipe_used_count int  NOT NULL,
                                like_count int  NOT NULL,
                                coffee_id int  NOT NULL,
                                average_rating double precision NOT NULL DEFAULT 0,
                                ranking_score double precision NOT NULL DEFAULT 0,
                                position integer NOT NULL DEFAULT 0,
                                CONSTRAINT coffee_ranking_pk PRIMARY KEY (id)
);

-- Table: coffee_rating
CREATE TABLE coffee_rating (
                               id int GENERATED BY DEFAULT AS IDENTITY,
                               value int  NOT NULL,
                               created_at timestamp  NOT NULL,
                               updated_at timestamp  NOT NULL,
                               user_id int  NOT NULL,
                               coffee_id int  NOT NULL,
                               CONSTRAINT coffee_rating_pk PRIMARY KEY (id)
);

-- Table: country
CREATE TABLE country (
                         id int GENERATED BY DEFAULT AS IDENTITY,
                         name varchar(255)  NOT NULL,
                         CONSTRAINT country_pk PRIMARY KEY (id)
);

-- Table: cupping_session
CREATE TABLE cupping_session (
                                 id int GENERATED BY DEFAULT AS IDENTITY,
                                 name varchar(255)  NOT NULL,
                                 description text  NULL,
                                 session_date timestamp NULL,
                                 created_at timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 user_id int  NOT NULL,
                                 CONSTRAINT cupping_session_pk PRIMARY KEY (id)
);
-- Table: cupping_session_coffee
CREATE TABLE cupping_session_coffee (
                                        id int GENERATED BY DEFAULT AS IDENTITY,
                                        notes text  NULL,
                                        aroma_score int NULL,
                                        sweetness_score int NULL,
                                        acidity_score int NULL,
                                        body_score int NULL,
                                        flavor_profile_notes text NULL,
                                        clean_cup boolean NULL,
                                        overall_score int NULL,
                                        created_at timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        coffee_id int  NOT NULL,
                                        cupping_session_id int  NOT NULL,
                                        CONSTRAINT cupping_session_coffee_pk PRIMARY KEY (id),
                                        CONSTRAINT uq_session_coffee UNIQUE (cupping_session_id, coffee_id)
);

-- Table: follow
CREATE TABLE follow (
                        follower_id int  NOT NULL,
                        followed_id int  NOT NULL,
                        created_at timestamp  NOT NULL,
                        CONSTRAINT follow_pk PRIMARY KEY (follower_id,followed_id)
);

-- Table: notification
CREATE TABLE notification (
                              id int GENERATED BY DEFAULT AS IDENTITY,
                              user_id int  NOT NULL,
                              content text  NOT NULL,
                              created_at timestamp  NOT NULL,
                              CONSTRAINT notification_pk PRIMARY KEY (id)
);

-- Table: processing_method
CREATE TABLE processing_method (
                                   id int GENERATED BY DEFAULT AS IDENTITY,
                                   name varchar(255)  NOT NULL,
                                   CONSTRAINT processing_method_pk PRIMARY KEY (id)
);

-- Table: quick_note
CREATE TABLE quick_note (
                            id int GENERATED BY DEFAULT AS IDENTITY,
                            content text  NOT NULL,
                            created_at timestamp  NOT NULL,
                            updated_at timestamp  NOT NULL,
                            user_id int  NOT NULL,
                            CONSTRAINT quick_note_pk PRIMARY KEY (id)
);

-- Table: recipe
CREATE TABLE recipe (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        title varchar(255)  NOT NULL,
                        parameters jsonb  NOT NULL,
                        steps text  NOT NULL,
                        is_public boolean  NOT NULL,
                        user_id int  NOT NULL,
                        brewing_method_id int,
                        coffee_id int,
                        created_at timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT recipe_pk PRIMARY KEY (id)
);

-- Table: recipe_ranking
CREATE TABLE recipe_ranking (
                                id int GENERATED BY DEFAULT AS IDENTITY,
                                refreshed_at timestamp  NOT NULL,
                                rating_count int  NOT NULL,
                                like_count int  NOT NULL,
                                save_count int  NOT NULL,
                                recipe_id int  NOT NULL,
                                position integer NOT NULL DEFAULT 0,
                                average_rating double precision NOT NULL DEFAULT 0,
                                ranking_score double precision NOT NULL DEFAULT 0,
                                CONSTRAINT recipe_ranking_pk PRIMARY KEY (id)
);

-- Table: recipe_rating
CREATE TABLE recipe_rating (
                               id int GENERATED BY DEFAULT AS IDENTITY,
                               value int  NOT NULL,
                               created_at timestamp  NOT NULL,
                               updated_at timestamp  NOT NULL,
                               user_id int  NOT NULL,
                               recipe_id int  NOT NULL,
                               CONSTRAINT recipe_rating_pk PRIMARY KEY (id)
);

-- Table: recommendations
CREATE TABLE recommendations (
                                 id int GENERATED BY DEFAULT AS IDENTITY,
                                 feedback boolean  NOT NULL,
                                 score int  NOT NULL,
                                 algorithm varchar(30)  NOT NULL,
                                 generated_at timestamp  NOT NULL,
                                 feedback_at timestamp  NULL,
                                 source text  NOT NULL,
                                 coffee_id int  NULL,
                                 recipe_id int  NULL,
                                 user_id int  NOT NULL,
                                 user_preference_id int  NULL,
                                 coffee_ranking_id int  NULL,
                                 CONSTRAINT recommendations_pk PRIMARY KEY (id)
);

-- Table: region
CREATE TABLE region (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        name varchar(255)  NOT NULL,
                        country_id int  NOT NULL,
                        CONSTRAINT region_pk PRIMARY KEY (id)
);

-- Table: roastery
CREATE TABLE roastery (
                          id int GENERATED BY DEFAULT AS IDENTITY,
                          name varchar(255)  NOT NULL,
                          CONSTRAINT roastery_pk PRIMARY KEY (id)
);

-- Table: user_preference
CREATE TABLE user_preference (
                                 id int GENERATED BY DEFAULT AS IDENTITY,
                                 preferred_roast_level varchar(255)  NOT NULL,
                                 favorite_notes text  NOT NULL,
                                 quiz_completed boolean  NOT NULL,
                                 user_id int  NOT NULL,
                                 CONSTRAINT user_preference_pk PRIMARY KEY (id)
);

-- Table: user_ranking
CREATE TABLE user_ranking (
                              id int GENERATED BY DEFAULT AS IDENTITY,
                              refreshed_at timestamp  NOT NULL,
                              activity_score int  NOT NULL,
                              recipe_count int  NOT NULL,
                              like_count int  NOT NULL,
                              user_id int  NOT NULL,
                              position integer NOT NULL DEFAULT 0,
                              public_recipe_count integer NOT NULL DEFAULT 0,
                              coffee_rating_count integer NOT NULL DEFAULT 0,
                              recipe_rating_count integer NOT NULL DEFAULT 0,
                              quick_note_count integer NOT NULL DEFAULT 0,
                              cupping_session_count integer NOT NULL DEFAULT 0,
                              cupping_session_coffee_count integer NOT NULL DEFAULT 0,
                              followers_count integer NOT NULL DEFAULT 0,
                              received_recipe_favorite_count integer NOT NULL DEFAULT 0,
                              published_article_count integer NOT NULL DEFAULT 0,
                              CONSTRAINT user_ranking_pk PRIMARY KEY (id)
);

-- Table: variety
CREATE TABLE variety (
                         id int GENERATED BY DEFAULT AS IDENTITY,
                         name varchar(255)  NOT NULL,
                         CONSTRAINT variety_pk PRIMARY KEY (id)
);

-- Table: app_user
CREATE TABLE app_user (
                          id int GENERATED BY DEFAULT AS IDENTITY,
                          email varchar(255)  NOT NULL UNIQUE,
                          password_hash varchar(255)  NOT NULL,
                          login varchar(50)  NOT NULL UNIQUE,
                          role varchar(50)  NOT NULL,
                          activity_points int  NOT NULL DEFAULT 0,
                          label varchar(255)  NULL,
                          is_blocked boolean  NOT NULL DEFAULT FALSE,
                          created_at timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT app_user_pk PRIMARY KEY (id)
);

-- Table: user_recipe_favorite
CREATE TABLE user_recipe_favorite (
    user_id int NOT NULL,
    recipe_id int NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_recipe_favorite_pk PRIMARY KEY (user_id, recipe_id)
);

-- Table: user_coffee_favorite
CREATE TABLE user_coffee_favorite (
    user_id int NOT NULL,
    coffee_id int NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_coffee_favorite_pk PRIMARY KEY (user_id, coffee_id)
);

-- 
CREATE TABLE report (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        reason text NOT NULL,
                        created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        article_id int NOT NULL,
                        reported_by_user_id int NOT NULL,

                        CONSTRAINT report_pk PRIMARY KEY (id),

                        CONSTRAINT report_article_fk
                            FOREIGN KEY (article_id)
                                REFERENCES article(id),

                        CONSTRAINT report_user_fk
                            FOREIGN KEY (reported_by_user_id)
                                REFERENCES app_user(id)
);

-- foreign keys
-- Reference: article_moderator_user (table: article)
ALTER TABLE article ADD CONSTRAINT article_moderator_user
    FOREIGN KEY (moderated_by_user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: article_user (table: article)
ALTER TABLE article ADD CONSTRAINT article_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: article_coffee_fk (table: article)
ALTER TABLE article ADD CONSTRAINT article_coffee_fk
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;


-- Reference: coffee_processing_methods (table: coffee)
ALTER TABLE coffee ADD CONSTRAINT coffee_processing_methods
    FOREIGN KEY (processing_method_id)
        REFERENCES processing_method (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: coffee_regions (table: coffee)
ALTER TABLE coffee ADD CONSTRAINT coffee_regions
    FOREIGN KEY (region_id)
        REFERENCES region (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: coffee_roasteries (table: coffee)
ALTER TABLE coffee ADD CONSTRAINT coffee_roasteries
    FOREIGN KEY (roastery_id)
        REFERENCES roastery (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: coffee_user (table: coffee)
ALTER TABLE coffee ADD CONSTRAINT coffee_user
    FOREIGN KEY (created_by_user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: coffee_varieties (table: coffee)
ALTER TABLE coffee ADD CONSTRAINT coffee_varieties
    FOREIGN KEY (variety_id)
        REFERENCES variety (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: cupping_session_user (table: cupping_session)
ALTER TABLE cupping_session ADD CONSTRAINT cupping_session_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: cupping_session_coffee_coffee (table: cupping_session_coffee)
ALTER TABLE cupping_session_coffee ADD CONSTRAINT cupping_session_coffee_coffee
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: cupping_session_coffee_session (table: cupping_session_coffee)
ALTER TABLE cupping_session_coffee ADD CONSTRAINT cupping_session_coffee_session
    FOREIGN KEY (cupping_session_id)
        REFERENCES cupping_session (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: followed_user (table: follow)
ALTER TABLE follow ADD CONSTRAINT followed_user
    FOREIGN KEY (followed_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: follower_user (table: follow)
ALTER TABLE follow ADD CONSTRAINT follower_user
    FOREIGN KEY (follower_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: notification_user (table: notification)
ALTER TABLE notification ADD CONSTRAINT notification_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: quick_notes_user (table: quick_note)
ALTER TABLE quick_note ADD CONSTRAINT quick_notes_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: ranking_coffee_coffee (table: coffee_ranking)
ALTER TABLE coffee_ranking ADD CONSTRAINT ranking_coffee_coffee
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: ranking_recipe_recipe (table: recipe_ranking)
ALTER TABLE recipe_ranking ADD CONSTRAINT ranking_recipe_recipe
    FOREIGN KEY (recipe_id)
        REFERENCES recipe (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: ranking_user_user (table: user_ranking)
ALTER TABLE user_ranking ADD CONSTRAINT ranking_user_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: rating_coffee_coffee (table: coffee_rating)
ALTER TABLE coffee_rating ADD CONSTRAINT rating_coffee_coffee
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: rating_coffee_user (table: coffee_rating)
ALTER TABLE coffee_rating ADD CONSTRAINT rating_coffee_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: rating_recipe_recipes (table: recipe_rating)
ALTER TABLE recipe_rating ADD CONSTRAINT rating_recipe_recipes
    FOREIGN KEY (recipe_id)
        REFERENCES recipe (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: rating_recipe_user (table: recipe_rating)
ALTER TABLE recipe_rating ADD CONSTRAINT rating_recipe_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recipes_brewing_methods (table: recipe)
ALTER TABLE recipe ADD CONSTRAINT recipes_brewing_methods
    FOREIGN KEY (brewing_method_id)
        REFERENCES brewing_method (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recipes_user (table: recipe)
ALTER TABLE recipe ADD CONSTRAINT recipes_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recipes_coffee (table: recipe)
ALTER TABLE recipe ADD CONSTRAINT recipes_coffee
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recommendations_coffee (table: recommendations)
ALTER TABLE recommendations ADD CONSTRAINT recommendations_coffee
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recommendations_ranking_coffee (table: recommendations)
ALTER TABLE recommendations ADD CONSTRAINT recommendations_ranking_coffee
    FOREIGN KEY (coffee_ranking_id)
        REFERENCES coffee_ranking (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recommendations_recipe (table: recommendations)
ALTER TABLE recommendations ADD CONSTRAINT recommendations_recipe
    FOREIGN KEY (recipe_id)
        REFERENCES recipe (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recommendations_user (table: recommendations)
ALTER TABLE recommendations ADD CONSTRAINT recommendations_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recommendations_user_preferences (table: recommendations)
ALTER TABLE recommendations ADD CONSTRAINT recommendations_user_preferences
    FOREIGN KEY (user_preference_id)
        REFERENCES user_preference (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: region_country (table: region)
ALTER TABLE region ADD CONSTRAINT region_country
    FOREIGN KEY (country_id)
        REFERENCES country (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: user_preferences_user (table: user_preference)
ALTER TABLE user_preference ADD CONSTRAINT user_preferences_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: user_recipe_favorite_user (table: user_recipe_favorite)
ALTER TABLE user_recipe_favorite ADD CONSTRAINT user_recipe_favorite_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: user_recipe_favorite_recipe (table: user_recipe_favorite)
ALTER TABLE user_recipe_favorite ADD CONSTRAINT user_recipe_favorite_recipe
    FOREIGN KEY (recipe_id)
        REFERENCES recipe (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: user_coffee_favorite_user (table: user_coffee_favorite)
ALTER TABLE user_coffee_favorite ADD CONSTRAINT user_coffee_favorite_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: user_coffee_favorite_coffee (table: user_coffee_favorite)
ALTER TABLE user_coffee_favorite ADD CONSTRAINT user_coffee_favorite_coffee
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;


-- =====================
-- CHECK Constraints
-- =====================
ALTER TABLE recommendations ADD CONSTRAINT chk_recommendation_target
    CHECK ( (coffee_id IS NOT NULL AND recipe_id IS NULL) OR (coffee_id IS NULL AND recipe_id IS NOT NULL)
        );

-- coffee_rating: zakres oceny 1-5
ALTER TABLE coffee_rating ADD CONSTRAINT chk_coffee_rating_value
    CHECK (value BETWEEN 1 AND 5);

-- recipe_rating: zakres oceny 1-5
ALTER TABLE recipe_rating ADD CONSTRAINT chk_recipe_rating_value
    CHECK (value BETWEEN 1 AND 5);

-- =====================
-- INDEXES (ALL FOREIGN KEYS)
-- =====================

-- article
CREATE INDEX idx_article_user_id ON article(user_id);
CREATE INDEX idx_article_coffee_id ON article(coffee_id);
CREATE UNIQUE INDEX uq_article_coffee_wiki
    ON article(coffee_id)
    WHERE module = 'coffee'
      AND status = 'Approved'
      AND coffee_id IS NOT NULL;
CREATE INDEX idx_article_moderated_by_user_id ON article(moderated_by_user_id);

-- coffee
CREATE INDEX idx_coffee_created_by_user_id ON coffee(created_by_user_id);
CREATE INDEX idx_coffee_region_id ON coffee(region_id);
CREATE INDEX idx_coffee_roastery_id ON coffee(roastery_id);
CREATE INDEX idx_coffee_processing_method_id ON coffee(processing_method_id);
CREATE INDEX idx_coffee_variety_id ON coffee(variety_id);

-- coffee_rating
CREATE INDEX idx_coffee_rating_user_id ON coffee_rating(user_id);
CREATE INDEX idx_coffee_rating_coffee_id ON coffee_rating(coffee_id);

-- coffee_ranking
CREATE INDEX idx_coffee_ranking_coffee_id ON coffee_ranking(coffee_id);

-- recipe
CREATE INDEX idx_recipe_user_id ON recipe(user_id);
CREATE INDEX idx_recipe_coffee_id ON recipe(coffee_id);
CREATE INDEX idx_recipe_brewing_method_id ON recipe(brewing_method_id);

-- recipe_rating
CREATE INDEX idx_recipe_rating_user_id ON recipe_rating(user_id);
CREATE INDEX idx_recipe_rating_recipe_id ON recipe_rating(recipe_id);

-- recipe_ranking
CREATE INDEX idx_recipe_ranking_recipe_id ON recipe_ranking(recipe_id);

-- recommendations
CREATE INDEX idx_recommendations_user_id ON recommendations(user_id);
CREATE INDEX idx_recommendations_coffee_id ON recommendations(coffee_id);
CREATE INDEX idx_recommendations_recipe_id ON recommendations(recipe_id);
CREATE INDEX idx_recommendations_user_preference_id ON recommendations(user_preference_id);
CREATE INDEX idx_recommendations_coffee_ranking_id ON recommendations(coffee_ranking_id);

-- user_preference
CREATE INDEX idx_user_preference_user_id ON user_preference(user_id);

-- user_ranking
CREATE INDEX idx_user_ranking_user_id ON user_ranking(user_id);

-- user_recipe_favorite
CREATE INDEX idx_user_recipe_favorite_recipe_id ON user_recipe_favorite(recipe_id);

-- user_coffee_favorite
CREATE INDEX idx_user_coffee_favorite_coffee_id ON user_coffee_favorite(coffee_id);

-- cupping_session
CREATE INDEX idx_cupping_session_user_id ON cupping_session(user_id);

-- cupping_session_coffee
CREATE INDEX idx_cupping_session_coffee_coffee_id ON cupping_session_coffee(coffee_id);
CREATE INDEX idx_cupping_session_coffee_cupping_session_id ON cupping_session_coffee(cupping_session_id);

-- notification
CREATE INDEX idx_notification_user_id ON notification(user_id);

-- quick_note
CREATE INDEX idx_quick_note_user_id ON quick_note(user_id);

-- region
CREATE INDEX idx_region_country_id ON region(country_id);

-- follow
CREATE INDEX idx_follow_followed_id ON follow(followed_id);

-- report
CREATE INDEX idx_report_article_id ON report(article_id);
CREATE INDEX idx_report_reported_by_user_id ON report(reported_by_user_id);

-- =====================
-- Global search (extensions, immutable text wrapper, trigram indexes)
-- Incremental equivalent: migrations/013_global_search_extensions.sql
-- =====================

CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_extension e
        JOIN pg_namespace n ON n.oid = e.extnamespace
        WHERE e.extname = 'unaccent'
          AND n.nspname <> 'public'
    ) THEN
        ALTER EXTENSION unaccent SET SCHEMA public;
    END IF;
END $$;

CREATE OR REPLACE FUNCTION brewbase_search_text(input text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
STRICT
SET search_path TO public, extensions, pg_catalog
AS $$
    SELECT unaccent('unaccent'::regdictionary, lower(input))
$$;

CREATE INDEX idx_coffee_name_search
    ON coffee USING gin (brewbase_search_text(name) gin_trgm_ops);

CREATE INDEX idx_recipe_title_search
    ON recipe USING gin (brewbase_search_text(title) gin_trgm_ops);

CREATE INDEX idx_article_title_search
    ON article USING gin (brewbase_search_text(title) gin_trgm_ops);

CREATE INDEX idx_article_content_search
    ON article USING gin (brewbase_search_text(content) gin_trgm_ops);

CREATE INDEX idx_app_user_login_search
    ON app_user USING gin (brewbase_search_text(login) gin_trgm_ops);

CREATE INDEX idx_app_user_label_search
    ON app_user USING gin (brewbase_search_text(COALESCE(label, '')) gin_trgm_ops);

CREATE INDEX idx_quick_note_content_search
    ON quick_note USING gin (brewbase_search_text(content) gin_trgm_ops);

CREATE INDEX idx_cupping_session_name_search
    ON cupping_session USING gin (brewbase_search_text(name) gin_trgm_ops);

-- =====================
-- Ranking refresh functions (required by backend; no pg_cron)
-- =====================

CREATE OR REPLACE FUNCTION refresh_coffee_ranking()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
DROP TABLE IF EXISTS tmp_coffee_ranking;

CREATE TEMP TABLE tmp_coffee_ranking ON COMMIT DROP AS
SELECT
    row_number() OVER (
            ORDER BY
                AVG(cr.value)::double precision DESC,
                COUNT(cr.id) DESC,
                COUNT(DISTINCT ucf.user_id) DESC,
                COUNT(DISTINCT r.id) DESC,
                c.name ASC
        )::integer AS position,
        c.id AS coffee_id,
        AVG(cr.value)::double precision AS average_rating,
        COUNT(cr.id)::integer AS rating_count,
        COUNT(DISTINCT r.id)::integer AS recipe_used_count,
        COUNT(DISTINCT ucf.user_id)::integer AS like_count,
        (
            AVG(cr.value)::double precision * 100
            + COUNT(cr.id)::double precision * 2
            + COUNT(DISTINCT r.id)::double precision
            + COUNT(DISTINCT ucf.user_id)::double precision
        ) AS ranking_score,
        CURRENT_TIMESTAMP::timestamp without time zone AS refreshed_at
FROM coffee c
    JOIN coffee_rating cr ON cr.coffee_id = c.id
    LEFT JOIN recipe r ON r.coffee_id = c.id
    LEFT JOIN user_coffee_favorite ucf ON ucf.coffee_id = c.id
GROUP BY c.id, c.name;

UPDATE coffee_ranking target
SET
    position = source.position,
    average_rating = source.average_rating,
    rating_count = source.rating_count,
    recipe_used_count = source.recipe_used_count,
    like_count = source.like_count,
    ranking_score = source.ranking_score,
    refreshed_at = source.refreshed_at
    FROM tmp_coffee_ranking source
WHERE target.coffee_id = source.coffee_id;

INSERT INTO coffee_ranking (
    refreshed_at,
    rating_count,
    recipe_used_count,
    like_count,
    coffee_id,
    position,
    average_rating,
    ranking_score
)
SELECT
    source.refreshed_at,
    source.rating_count,
    source.recipe_used_count,
    source.like_count,
    source.coffee_id,
    source.position,
    source.average_rating,
    source.ranking_score
FROM tmp_coffee_ranking source
WHERE NOT EXISTS (
    SELECT 1
    FROM coffee_ranking target
    WHERE target.coffee_id = source.coffee_id
);

UPDATE coffee_ranking target
SET
    position = 0,
    average_rating = 0,
    rating_count = 0,
    recipe_used_count = 0,
    like_count = 0,
    ranking_score = 0,
    refreshed_at = CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1
    FROM tmp_coffee_ranking source
    WHERE source.coffee_id = target.coffee_id
);
END;
$$;

CREATE OR REPLACE FUNCTION refresh_recipe_ranking()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
DROP TABLE IF EXISTS tmp_recipe_ranking;

CREATE TEMP TABLE tmp_recipe_ranking ON COMMIT DROP AS
SELECT
    row_number() OVER (
            ORDER BY
                AVG(rr.value)::double precision DESC,
                COUNT(rr.id) DESC,
                COUNT(urf.recipe_id) DESC,
                r.title ASC
        )::integer AS position,
        r.id AS recipe_id,
        AVG(rr.value)::double precision AS average_rating,
        COUNT(rr.id)::integer AS rating_count,
        COUNT(urf.recipe_id)::integer AS save_count,
        COUNT(urf.recipe_id)::integer AS like_count,
        (
            AVG(rr.value)::double precision * 100
            + COUNT(rr.id)::double precision * 2
            + COUNT(urf.recipe_id)::double precision
        ) AS ranking_score,
        CURRENT_TIMESTAMP::timestamp without time zone AS refreshed_at
FROM recipe r
    JOIN recipe_rating rr ON rr.recipe_id = r.id
    LEFT JOIN user_recipe_favorite urf ON urf.recipe_id = r.id
WHERE r.is_public = true
GROUP BY r.id, r.title;

UPDATE recipe_ranking target
SET
    position = source.position,
    average_rating = source.average_rating,
    rating_count = source.rating_count,
    like_count = source.like_count,
    save_count = source.save_count,
    ranking_score = source.ranking_score,
    refreshed_at = source.refreshed_at
    FROM tmp_recipe_ranking source
WHERE target.recipe_id = source.recipe_id;

INSERT INTO recipe_ranking (
    refreshed_at,
    rating_count,
    like_count,
    save_count,
    recipe_id,
    position,
    average_rating,
    ranking_score
)
SELECT
    source.refreshed_at,
    source.rating_count,
    source.like_count,
    source.save_count,
    source.recipe_id,
    source.position,
    source.average_rating,
    source.ranking_score
FROM tmp_recipe_ranking source
WHERE NOT EXISTS (
    SELECT 1
    FROM recipe_ranking target
    WHERE target.recipe_id = source.recipe_id
);

UPDATE recipe_ranking target
SET
    position = 0,
    average_rating = 0,
    rating_count = 0,
    like_count = 0,
    save_count = 0,
    ranking_score = 0,
    refreshed_at = CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1
    FROM tmp_recipe_ranking source
    WHERE source.recipe_id = target.recipe_id
);
END;
$$;

CREATE OR REPLACE FUNCTION refresh_user_ranking()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
DROP TABLE IF EXISTS tmp_user_ranking;

CREATE TEMP TABLE tmp_user_ranking ON COMMIT DROP AS
    WITH user_activity AS (
        SELECT
            u.id AS user_id,
            (
                SELECT COUNT(*)
                FROM recipe r
                WHERE r.user_id = u.id
                  AND r.is_public = true
            )::integer AS public_recipe_count,
            (
                SELECT COUNT(*)
                FROM coffee_rating cr
                WHERE cr.user_id = u.id
            )::integer AS coffee_rating_count,
            (
                SELECT COUNT(*)
                FROM recipe_rating rr
                WHERE rr.user_id = u.id
            )::integer AS recipe_rating_count,
            (
                SELECT COUNT(*)
                FROM quick_note qn
                WHERE qn.user_id = u.id
            )::integer AS quick_note_count,
            (
                SELECT COUNT(*)
                FROM cupping_session cs
                WHERE cs.user_id = u.id
            )::integer AS cupping_session_count,
            (
                SELECT COUNT(*)
                FROM cupping_session cs
                JOIN cupping_session_coffee csc ON csc.cupping_session_id = cs.id
                WHERE cs.user_id = u.id
            )::integer AS cupping_session_coffee_count,
            (
                SELECT COUNT(*)
                FROM follow f
                WHERE f.followed_id = u.id
            )::integer AS followers_count,
            (
                SELECT COUNT(*)
                FROM recipe r
                JOIN user_recipe_favorite urf ON urf.recipe_id = r.id
                WHERE r.user_id = u.id
            )::integer AS received_recipe_favorite_count,
            (
                SELECT COUNT(*)
                FROM article a
                WHERE a.user_id = u.id
                  AND UPPER(a.status) = 'APPROVED'
            )::integer AS published_article_count
        FROM app_user u
        WHERE COALESCE(u.is_blocked, false) = false
    ),
    scored_users AS (
        SELECT
            user_id,
            public_recipe_count,
            coffee_rating_count,
            recipe_rating_count,
            quick_note_count,
            cupping_session_count,
            cupping_session_coffee_count,
            followers_count,
            received_recipe_favorite_count,
            published_article_count,
            (
                public_recipe_count * 10
                + coffee_rating_count * 3
                + recipe_rating_count * 3
                + quick_note_count * 2
                + cupping_session_count * 8
                + cupping_session_coffee_count * 2
                + followers_count * 5
                + received_recipe_favorite_count * 4
                + published_article_count * 12
            )::integer AS activity_score
        FROM user_activity
    )
SELECT
    row_number() OVER (
            ORDER BY
                su.activity_score DESC,
                su.public_recipe_count DESC,
                su.followers_count DESC,
                u.login ASC
        )::integer AS position,
        su.user_id,
        su.activity_score,
        su.public_recipe_count,
        su.coffee_rating_count,
        su.recipe_rating_count,
        su.quick_note_count,
        su.cupping_session_count,
        su.cupping_session_coffee_count,
        su.followers_count,
        su.received_recipe_favorite_count,
        su.published_article_count,
        CURRENT_TIMESTAMP::timestamp without time zone AS refreshed_at
FROM scored_users su
    JOIN app_user u ON u.id = su.user_id
WHERE su.activity_score > 0;

UPDATE user_ranking target
SET
    position = source.position,
    activity_score = source.activity_score,
    recipe_count = source.public_recipe_count,
    like_count = source.received_recipe_favorite_count,
    public_recipe_count = source.public_recipe_count,
    coffee_rating_count = source.coffee_rating_count,
    recipe_rating_count = source.recipe_rating_count,
    quick_note_count = source.quick_note_count,
    cupping_session_count = source.cupping_session_count,
    cupping_session_coffee_count = source.cupping_session_coffee_count,
    followers_count = source.followers_count,
    received_recipe_favorite_count = source.received_recipe_favorite_count,
    published_article_count = source.published_article_count,
    refreshed_at = source.refreshed_at
    FROM tmp_user_ranking source
WHERE target.user_id = source.user_id;

INSERT INTO user_ranking (
    refreshed_at,
    activity_score,
    recipe_count,
    like_count,
    user_id,
    position,
    public_recipe_count,
    coffee_rating_count,
    recipe_rating_count,
    quick_note_count,
    cupping_session_count,
    cupping_session_coffee_count,
    followers_count,
    received_recipe_favorite_count,
    published_article_count
)
SELECT
    source.refreshed_at,
    source.activity_score,
    source.public_recipe_count,
    source.received_recipe_favorite_count,
    source.user_id,
    source.position,
    source.public_recipe_count,
    source.coffee_rating_count,
    source.recipe_rating_count,
    source.quick_note_count,
    source.cupping_session_count,
    source.cupping_session_coffee_count,
    source.followers_count,
    source.received_recipe_favorite_count,
    source.published_article_count
FROM tmp_user_ranking source
WHERE NOT EXISTS (
    SELECT 1
    FROM user_ranking target
    WHERE target.user_id = source.user_id
);

UPDATE user_ranking target
SET
    position = 0,
    activity_score = 0,
    recipe_count = 0,
    like_count = 0,
    public_recipe_count = 0,
    coffee_rating_count = 0,
    recipe_rating_count = 0,
    quick_note_count = 0,
    cupping_session_count = 0,
    cupping_session_coffee_count = 0,
    followers_count = 0,
    received_recipe_favorite_count = 0,
    published_article_count = 0,
    refreshed_at = CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1
    FROM tmp_user_ranking source
    WHERE source.user_id = target.user_id
);
END;
$$;

CREATE OR REPLACE FUNCTION refresh_all_rankings()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM refresh_coffee_ranking();
    PERFORM refresh_recipe_ranking();
    PERFORM refresh_user_ranking();
END;
$$;