-- WIP database schema generated from ERD
-- schema still requires cleanup and review
-- naming consistency and indexes are not finalized yet
    
-- Last modification date: 2026-03-18 09:39:04.822

-- tables
-- Table: Article
CREATE TABLE Article (
                         id int GENERATED BY DEFAULT AS IDENTITY,
                         title varchar(30)  NOT NULL,
                         content text  NOT NULL,
                         status varchar(25)  NOT NULL,
                         created_at timestamp  NOT NULL,
                         updated_at timestamp  NOT NULL,
                         published_at timestamp  NULL,
                         moderated_by int  NULL,
                         moderated_at timestamp  NULL,
                         moderation_comment text  NULL,
                         user_id int  NOT NULL,
                         CONSTRAINT Article_pk PRIMARY KEY (id)
);

-- Table: Brewing_Method
CREATE TABLE Brewing_Method (
                                id int GENERATED BY DEFAULT AS IDENTITY,
                                name varchar  NOT NULL,
                                description text  NOT NULL,
                                CONSTRAINT Brewing_Method_pk PRIMARY KEY (id)
);

-- Table: Coffee
CREATE TABLE Coffee (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        name varchar(255)  NOT NULL,
                        Roastery_id int  NOT NULL,
                        Region_id int  NOT NULL,
                        Variety_id int  NULL,
                        Processing_method_id int  NULL,
                        created_by int  NOT NULL,
                        is_verified boolean  NOT NULL,
                        Cupping_session_id int  NULL,
                        CONSTRAINT Coffee_pk PRIMARY KEY (ID)
);

-- Table: Coffee_Ranking
CREATE TABLE Coffee_Ranking (
                                id int GENERATED BY DEFAULT AS IDENTITY,
                                refreshed_at timestamp  NOT NULL,
                                rating_count int  NOT NULL,
                                recipe_used_count int  NOT NULL,
                                like_count int  NOT NULL,
                                Coffee_id int  NOT NULL,
                                CONSTRAINT Coffee_Ranking_pk PRIMARY KEY (id)
);

-- Table: Coffee_Rating
CREATE TABLE Coffee_Rating (
                               id int GENERATED BY DEFAULT AS IDENTITY,
                               value int  NOT NULL,
                               created_at timestamp  NOT NULL,
                               updated_at timestamp  NOT NULL,
                               User_id int  NOT NULL,
                               Coffee_id int  NOT NULL,
                               CONSTRAINT Coffee_Rating_pk PRIMARY KEY (id)
);

-- Table: Country
CREATE TABLE Country (
                         id int GENERATED BY DEFAULT AS IDENTITY,
                         name varchar  NOT NULL,
                         CONSTRAINT Country_pk PRIMARY KEY (id)
);

-- Table: Cupping_Session
CREATE TABLE Cupping_Session (
                                 id int GENERATED BY DEFAULT AS IDENTITY,
                                 name varchar(150)  NOT NULL,
                                 notes text  NOT NULL,
                                 User_id int  NOT NULL,
                                 CONSTRAINT Cupping_Session_pk PRIMARY KEY (id)
);

-- Table: Follow
CREATE TABLE Follow (
                        follower_id int  NOT NULL,
                        followed_id int  NOT NULL,
                        created_at timestamp  NOT NULL,
                        CONSTRAINT Follow_pk PRIMARY KEY (follower_id,followed_id)
);

-- Table: Notification
CREATE TABLE Notification (
                              id int GENERATED BY DEFAULT AS IDENTITY,
                              User_id int  NOT NULL,
                              content text  NOT NULL,
                              created_at timestamp  NOT NULL,
                              CONSTRAINT Notification_pk PRIMARY KEY (id)
);

-- Table: Processing_Method
CREATE TABLE Processing_Method (
                                   id int GENERATED BY DEFAULT AS IDENTITY,
                                   name varchar  NOT NULL,
                                   CONSTRAINT Processing_Method_pk PRIMARY KEY (id)
);

-- Table: Quick_Note
CREATE TABLE Quick_Note (
                            id int GENERATED BY DEFAULT AS IDENTITY,
                            content text  NOT NULL,
                            created_at timestamp  NOT NULL,
                            updated_at timestamp  NOT NULL,
                            User_id int  NOT NULL,
                            CONSTRAINT Quick_Note_pk PRIMARY KEY (id)
);

-- Table: Recipe
CREATE TABLE Recipe (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        title varchar  NOT NULL,
                        parameter jsonb  NOT NULL,
                        steps text  NOT NULL,
                        is_public boolean  NOT NULL,
                        User_id int  NOT NULL,
                        Brewing_method_id int  NOT NULL,
                        Coffee_id int  NOT NULL,
                        CONSTRAINT Recipe_pk PRIMARY KEY (id)
);

-- Table: Recipe_Ranking
CREATE TABLE Recipe_Ranking (
                                id int GENERATED BY DEFAULT AS IDENTITY,
                                refreshed_at timestamp  NOT NULL,
                                rating_count int  NOT NULL,
                                like_count int  NOT NULL,
                                save_count int  NOT NULL,
                                Recipe_id int  NOT NULL,
                                CONSTRAINT Recipe_Ranking_pk PRIMARY KEY (id)
);

-- Table: Recipe_Rating
CREATE TABLE Recipe_Rating (
                               id int GENERATED BY DEFAULT AS IDENTITY,
                               value int  NOT NULL,
                               created_at timestamp  NOT NULL,
                               updated_at timestamp  NOT NULL,
                               User_id int  NOT NULL,
                               Recipe_id int  NOT NULL,
                               CONSTRAINT Recipe_Rating_pk PRIMARY KEY (id)
);

-- Table: Recommendations
CREATE TABLE Recommendations (
                                 id int GENERATED BY DEFAULT AS IDENTITY,
                                 feedback boolean  NOT NULL,
                                 score int  NOT NULL,
                                 algorithm varchar(30)  NOT NULL,
                                 generated_at timestamp  NOT NULL,
                                 feedback_at timestamp  NULL,
                                 source text  NOT NULL,
                                 Coffee_id int  NULL,
                                 Recipe_id int  NULL,
                                 User_id int  NOT NULL,
                                 User_Preference_id int  NULL,
                                 Coffee_Ranking_id int  NULL,
                                 CONSTRAINT Recommendations_pk PRIMARY KEY (id)
);

-- Table: Region
CREATE TABLE Region (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        name varchar  NOT NULL,
                        Country_id int  NOT NULL,
                        CONSTRAINT Region_pk PRIMARY KEY (ID)
);

-- Table: Roastery
CREATE TABLE Roastery (
                          id int GENERATED BY DEFAULT AS IDENTITY,
                          name varchar  NOT NULL,
                          CONSTRAINT Roastery_pk PRIMARY KEY (id)
);

-- Table: User_Preference
CREATE TABLE User_Preference (
                                 id int GENERATED BY DEFAULT AS IDENTITY,
                                 preferred_roast_level varchar  NOT NULL,
                                 favorite_notes text  NOT NULL,
                                 quiz_completed boolean  NOT NULL,
                                 User_id int  NOT NULL,
                                 CONSTRAINT User_Preference_pk PRIMARY KEY (id)
);

-- Table: User_Ranking
CREATE TABLE User_Ranking (
                              id int GENERATED BY DEFAULT AS IDENTITY,
                              refreshed_at timestamp  NOT NULL,
                              activity_score int  NOT NULL,
                              recipe_count int  NOT NULL,
                              like_count int  NOT NULL,
                              User_id int  NOT NULL,
                              CONSTRAINT User_Ranking_pk PRIMARY KEY (id)
);

-- Table: Variety
CREATE TABLE Variety (
                         id int GENERATED BY DEFAULT AS IDENTITY,
                         name varchar  NOT NULL,
                         CONSTRAINT Variety_pk PRIMARY KEY (id)
);

-- Table: app_user
CREATE TABLE app_user (
                          id int GENERATED BY DEFAULT AS IDENTITY,
                          email varchar(255)  NOT NULL,
                          password_hash varchar  NOT NULL,
                          login varchar(50)  NOT NULL,
                          role varchar(50)  NOT NULL,
                          activity_points int  NOT NULL,
                          label varchar  NULL,
                          is_blocked boolean  NOT NULL,
                          created_at timestamp  NOT NULL,
                          CONSTRAINT app_user_pk PRIMARY KEY (id)
);

-- foreign keys
-- Reference: Article_Moderator_User (table: Article)
ALTER TABLE Article ADD CONSTRAINT Article_Moderator_User
    FOREIGN KEY (moderated_by)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Article_User (table: Article)
ALTER TABLE Article ADD CONSTRAINT Article_User
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Coffee_Cupping_session (table: Coffee)
ALTER TABLE Coffee ADD CONSTRAINT Coffee_Cupping_session
    FOREIGN KEY (Cupping_session_id)
        REFERENCES Cupping_Session (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Coffee_Processing_methods (table: Coffee)
ALTER TABLE Coffee ADD CONSTRAINT Coffee_Processing_methods
    FOREIGN KEY (Processing_method_id)
        REFERENCES Processing_Method (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Coffee_Regions (table: Coffee)
ALTER TABLE Coffee ADD CONSTRAINT Coffee_Regions
    FOREIGN KEY (Region_id)
        REFERENCES Region (ID)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Coffee_Roasteries (table: Coffee)
ALTER TABLE Coffee ADD CONSTRAINT Coffee_Roasteries
    FOREIGN KEY (Roastery_id)
        REFERENCES Roastery (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Coffee_User (table: Coffee)
ALTER TABLE Coffee ADD CONSTRAINT Coffee_User
    FOREIGN KEY (created_by)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Coffee_Varieties (table: Coffee)
ALTER TABLE Coffee ADD CONSTRAINT Coffee_Varieties
    FOREIGN KEY (Variety_id)
        REFERENCES Variety (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Cupping_session_User (table: Cupping_Session)
ALTER TABLE Cupping_Session ADD CONSTRAINT Cupping_session_User
    FOREIGN KEY (User_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Followed_User (table: Follow)
ALTER TABLE Follow ADD CONSTRAINT Followed_User
    FOREIGN KEY (followed_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Follower_User (table: Follow)
ALTER TABLE Follow ADD CONSTRAINT Follower_User
    FOREIGN KEY (follower_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Notification_User (table: Notification)
ALTER TABLE Notification ADD CONSTRAINT Notification_User
    FOREIGN KEY (User_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Quick_notes_User (table: Quick_Note)
ALTER TABLE Quick_Note ADD CONSTRAINT Quick_notes_User
    FOREIGN KEY (User_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Ranking_Coffee_Coffee (table: Coffee_Ranking)
ALTER TABLE Coffee_Ranking ADD CONSTRAINT Ranking_Coffee_Coffee
    FOREIGN KEY (Coffee_id)
        REFERENCES Coffee (ID)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Ranking_Recipe_Recipe (table: Recipe_Ranking)
ALTER TABLE Recipe_Ranking ADD CONSTRAINT Ranking_Recipe_Recipe
    FOREIGN KEY (Recipe_id)
        REFERENCES Recipe (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Ranking_User_User (table: User_Ranking)
ALTER TABLE User_Ranking ADD CONSTRAINT Ranking_User_User
    FOREIGN KEY (User_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Rating_Coffee_Coffee (table: Coffee_Rating)
ALTER TABLE Coffee_Rating ADD CONSTRAINT Rating_Coffee_Coffee
    FOREIGN KEY (Coffee_id)
        REFERENCES Coffee (ID)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Rating_Coffee_User (table: Coffee_Rating)
ALTER TABLE Coffee_Rating ADD CONSTRAINT Rating_Coffee_User
    FOREIGN KEY (User_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Rating_Recipe_Recipes (table: Recipe_Rating)
ALTER TABLE Recipe_Rating ADD CONSTRAINT Rating_Recipe_Recipes
    FOREIGN KEY (Recipe_id)
        REFERENCES Recipe (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Rating_Recipe_User (table: Recipe_Rating)
ALTER TABLE Recipe_Rating ADD CONSTRAINT Rating_Recipe_User
    FOREIGN KEY (User_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Recipes_Brewing_methods (table: Recipe)
ALTER TABLE Recipe ADD CONSTRAINT Recipes_Brewing_methods
    FOREIGN KEY (Brewing_method_id)
        REFERENCES Brewing_Method (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Recipes_User (table: Recipe)
ALTER TABLE Recipe ADD CONSTRAINT Recipes_User
    FOREIGN KEY (User_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Recipes__Coffee (table: Recipe)
ALTER TABLE Recipe ADD CONSTRAINT Recipes__Coffee
    FOREIGN KEY (Coffee_id)
        REFERENCES Coffee (ID)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Recommendations_Coffee (table: Recommendations)
ALTER TABLE Recommendations ADD CONSTRAINT Recommendations_Coffee
    FOREIGN KEY (Coffee_id)
        REFERENCES Coffee (ID)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Recommendations_Ranking_Coffee (table: Recommendations)
ALTER TABLE Recommendations ADD CONSTRAINT Recommendations_Ranking_Coffee
    FOREIGN KEY (Coffee_Ranking_id)
        REFERENCES Coffee_Ranking (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Recommendations_Recipe (table: Recommendations)
ALTER TABLE Recommendations ADD CONSTRAINT Recommendations_Recipe
    FOREIGN KEY (Recipe_id)
        REFERENCES Recipe (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Recommendations_User (table: Recommendations)
ALTER TABLE Recommendations ADD CONSTRAINT Recommendations_User
    FOREIGN KEY (User_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Recommendations_User_Preferences (table: Recommendations)
ALTER TABLE Recommendations ADD CONSTRAINT Recommendations_User_Preferences
    FOREIGN KEY (User_Preference_id)
        REFERENCES User_Preference (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: Region_Country (table: Region)
ALTER TABLE Region ADD CONSTRAINT Region_Country
    FOREIGN KEY (Country_id)
        REFERENCES Country (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: User_Preferences_User (table: User_Preference)
ALTER TABLE User_Preference ADD CONSTRAINT User_Preferences_User
    FOREIGN KEY (User_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;