-- database schema generated from ERD
-- Last modification date: 2026-03-18 13:04:04.822

-- =====================
-- Tables
-- =====================

-- Table: article
CREATE TABLE article (
                         id int GENERATED BY DEFAULT AS IDENTITY,
                         title varchar(255)  NOT NULL,
                         content text  NOT NULL,
                         status varchar(50)  NOT NULL,
                         created_at timestamp  NOT NULL,
                         updated_at timestamp  NOT NULL,
                         published_at timestamp  NULL,
                         moderated_by_user_id int  NULL,
                         moderated_at timestamp  NULL,
                         moderation_comment text  NULL,
                         user_id int  NOT NULL,
                         CONSTRAINT article_pk PRIMARY KEY (id)
);

-- Table: brewing_method
CREATE TABLE brewing_method (
                                id int GENERATED BY DEFAULT AS IDENTITY,
                                name varchar(255)  NOT NULL,
                                description text  NOT NULL,
                                CONSTRAINT brewing_method_pk PRIMARY KEY (id)
);

-- Table: coffee
CREATE TABLE coffee (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        name varchar(255)  NOT NULL,
                        roastery_id int  NOT NULL,
                        region_id int  NOT NULL,
                        variety_id int  NULL,
                        processing_method_id int  NULL,
                        created_by_user_id int  NOT NULL,
                        is_verified boolean  NOT NULL,
                        cupping_session_id int  NULL,
                        CONSTRAINT coffee_pk PRIMARY KEY (id)
);

-- Table: coffee_ranking
CREATE TABLE coffee_ranking (
                                id int GENERATED BY DEFAULT AS IDENTITY,
                                refreshed_at timestamp  NOT NULL,
                                rating_count int  NOT NULL,
                                recipe_used_count int  NOT NULL,
                                like_count int  NOT NULL,
                                coffee_id int  NOT NULL,
                                CONSTRAINT coffee_ranking_pk PRIMARY KEY (id)
);

-- Table: coffee_rating
CREATE TABLE coffee_rating (
                               id int GENERATED BY DEFAULT AS IDENTITY,
                               value int  NOT NULL,
                               created_at timestamp  NOT NULL,
                               updated_at timestamp  NOT NULL,
                               user_id int  NOT NULL,
                               coffee_id int  NOT NULL,
                               CONSTRAINT coffee_rating_pk PRIMARY KEY (id)
);

-- Table: country
CREATE TABLE country (
                         id int GENERATED BY DEFAULT AS IDENTITY,
                         name varchar(255)  NOT NULL,
                         CONSTRAINT country_pk PRIMARY KEY (id)
);

-- Table: cupping_session
CREATE TABLE cupping_session (
                                 id int GENERATED BY DEFAULT AS IDENTITY,
                                 name varchar(255)  NOT NULL,
                                 notes text  NOT NULL,
                                 user_id int  NOT NULL,
                                 CONSTRAINT cupping_session_pk PRIMARY KEY (id)
);

-- Table: follow
CREATE TABLE follow (
                        follower_id int  NOT NULL,
                        followed_id int  NOT NULL,
                        created_at timestamp  NOT NULL,
                        CONSTRAINT follow_pk PRIMARY KEY (follower_id,followed_id)
);

-- Table: notification
CREATE TABLE notification (
                              id int GENERATED BY DEFAULT AS IDENTITY,
                              user_id int  NOT NULL,
                              content text  NOT NULL,
                              created_at timestamp  NOT NULL,
                              CONSTRAINT notification_pk PRIMARY KEY (id)
);

-- Table: processing_method
CREATE TABLE processing_method (
                                   id int GENERATED BY DEFAULT AS IDENTITY,
                                   name varchar(255)  NOT NULL,
                                   CONSTRAINT processing_method_pk PRIMARY KEY (id)
);

-- Table: quick_note
CREATE TABLE quick_note (
                            id int GENERATED BY DEFAULT AS IDENTITY,
                            content text  NOT NULL,
                            created_at timestamp  NOT NULL,
                            updated_at timestamp  NOT NULL,
                            user_id int  NOT NULL,
                            CONSTRAINT quick_note_pk PRIMARY KEY (id)
);

-- Table: recipe
CREATE TABLE recipe (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        title varchar(255)  NOT NULL,
                        parameters jsonb  NOT NULL,
                        steps text  NOT NULL,
                        is_public boolean  NOT NULL,
                        user_id int  NOT NULL,
                        brewing_method_id int  NOT NULL,
                        coffee_id int  NOT NULL,
                        CONSTRAINT recipe_pk PRIMARY KEY (id)
);

-- Table: recipe_ranking
CREATE TABLE recipe_ranking (
                                id int GENERATED BY DEFAULT AS IDENTITY,
                                refreshed_at timestamp  NOT NULL,
                                rating_count int  NOT NULL,
                                like_count int  NOT NULL,
                                save_count int  NOT NULL,
                                recipe_id int  NOT NULL,
                                CONSTRAINT recipe_ranking_pk PRIMARY KEY (id)
);

-- Table: recipe_rating
CREATE TABLE recipe_rating (
                               id int GENERATED BY DEFAULT AS IDENTITY,
                               value int  NOT NULL,
                               created_at timestamp  NOT NULL,
                               updated_at timestamp  NOT NULL,
                               user_id int  NOT NULL,
                               recipe_id int  NOT NULL,
                               CONSTRAINT recipe_rating_pk PRIMARY KEY (id)
);

-- Table: recommendations
CREATE TABLE recommendations (
                                 id int GENERATED BY DEFAULT AS IDENTITY,
                                 feedback boolean  NOT NULL,
                                 score int  NOT NULL,
                                 algorithm varchar(30)  NOT NULL,
                                 generated_at timestamp  NOT NULL,
                                 feedback_at timestamp  NULL,
                                 source text  NOT NULL,
                                 coffee_id int  NULL,
                                 recipe_id int  NULL,
                                 user_id int  NOT NULL,
                                 user_preference_id int  NULL,
                                 coffee_ranking_id int  NULL,
                                 CONSTRAINT recommendations_pk PRIMARY KEY (id)
);

-- Table: region
CREATE TABLE region (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        name varchar(255)  NOT NULL,
                        country_id int  NOT NULL,
                        CONSTRAINT region_pk PRIMARY KEY (id)
);

-- Table: roastery
CREATE TABLE roastery (
                          id int GENERATED BY DEFAULT AS IDENTITY,
                          name varchar(255)  NOT NULL,
                          CONSTRAINT roastery_pk PRIMARY KEY (id)
);

-- Table: user_preference
CREATE TABLE user_preference (
                                 id int GENERATED BY DEFAULT AS IDENTITY,
                                 preferred_roast_level varchar(255)  NOT NULL,
                                 favorite_notes text  NOT NULL,
                                 quiz_completed boolean  NOT NULL,
                                 user_id int  NOT NULL,
                                 CONSTRAINT user_preference_pk PRIMARY KEY (id)
);

-- Table: user_ranking
CREATE TABLE user_ranking (
                              id int GENERATED BY DEFAULT AS IDENTITY,
                              refreshed_at timestamp  NOT NULL,
                              activity_score int  NOT NULL,
                              recipe_count int  NOT NULL,
                              like_count int  NOT NULL,
                              user_id int  NOT NULL,
                              CONSTRAINT user_ranking_pk PRIMARY KEY (id)
);

-- Table: variety
CREATE TABLE variety (
                         id int GENERATED BY DEFAULT AS IDENTITY,
                         name varchar(255)  NOT NULL,
                         CONSTRAINT variety_pk PRIMARY KEY (id)
);

-- Table: app_user
CREATE TABLE app_user (
                          id int GENERATED BY DEFAULT AS IDENTITY,
                          email varchar(255)  NOT NULL UNIQUE,
                          password_hash varchar(255)  NOT NULL,
                          login varchar(50)  NOT NULL UNIQUE,
                          role varchar(50)  NOT NULL,
                          activity_points int  NOT NULL DEFAULT 0,
                          label varchar(255)  NULL,
                          is_blocked boolean  NOT NULL DEFAULT FALSE,
                          created_at timestamp  NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT app_user_pk PRIMARY KEY (id)
);

-- Table: user_recipe_favorite
CREATE TABLE user_recipe_favorite (
    user_id int NOT NULL,
    recipe_id int NOT NULL,
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_recipe_favorite_pk PRIMARY KEY (user_id, recipe_id)
);

-- foreign keys
-- Reference: article_moderator_user (table: article)
ALTER TABLE article ADD CONSTRAINT article_moderator_user
    FOREIGN KEY (moderated_by_user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: article_user (table: article)
ALTER TABLE article ADD CONSTRAINT article_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: coffee_cupping_session (table: coffee)
ALTER TABLE coffee ADD CONSTRAINT coffee_cupping_session
    FOREIGN KEY (cupping_session_id)
        REFERENCES cupping_session (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: coffee_processing_methods (table: coffee)
ALTER TABLE coffee ADD CONSTRAINT coffee_processing_methods
    FOREIGN KEY (processing_method_id)
        REFERENCES processing_method (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: coffee_regions (table: coffee)
ALTER TABLE coffee ADD CONSTRAINT coffee_regions
    FOREIGN KEY (region_id)
        REFERENCES region (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: coffee_roasteries (table: coffee)
ALTER TABLE coffee ADD CONSTRAINT coffee_roasteries
    FOREIGN KEY (roastery_id)
        REFERENCES roastery (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: coffee_user (table: coffee)
ALTER TABLE coffee ADD CONSTRAINT coffee_user
    FOREIGN KEY (created_by_user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: coffee_varieties (table: coffee)
ALTER TABLE coffee ADD CONSTRAINT coffee_varieties
    FOREIGN KEY (variety_id)
        REFERENCES variety (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: cupping_session_user (table: cupping_session)
ALTER TABLE cupping_session ADD CONSTRAINT cupping_session_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: followed_user (table: follow)
ALTER TABLE follow ADD CONSTRAINT followed_user
    FOREIGN KEY (followed_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: follower_user (table: follow)
ALTER TABLE follow ADD CONSTRAINT follower_user
    FOREIGN KEY (follower_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: notification_user (table: notification)
ALTER TABLE notification ADD CONSTRAINT notification_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: quick_notes_user (table: quick_note)
ALTER TABLE quick_note ADD CONSTRAINT quick_notes_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: ranking_coffee_coffee (table: coffee_ranking)
ALTER TABLE coffee_ranking ADD CONSTRAINT ranking_coffee_coffee
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: ranking_recipe_recipe (table: recipe_ranking)
ALTER TABLE recipe_ranking ADD CONSTRAINT ranking_recipe_recipe
    FOREIGN KEY (recipe_id)
        REFERENCES recipe (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: ranking_user_user (table: user_ranking)
ALTER TABLE user_ranking ADD CONSTRAINT ranking_user_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: rating_coffee_coffee (table: coffee_rating)
ALTER TABLE coffee_rating ADD CONSTRAINT rating_coffee_coffee
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: rating_coffee_user (table: coffee_rating)
ALTER TABLE coffee_rating ADD CONSTRAINT rating_coffee_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: rating_recipe_recipes (table: recipe_rating)
ALTER TABLE recipe_rating ADD CONSTRAINT rating_recipe_recipes
    FOREIGN KEY (recipe_id)
        REFERENCES recipe (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: rating_recipe_user (table: recipe_rating)
ALTER TABLE recipe_rating ADD CONSTRAINT rating_recipe_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recipes_brewing_methods (table: recipe)
ALTER TABLE recipe ADD CONSTRAINT recipes_brewing_methods
    FOREIGN KEY (brewing_method_id)
        REFERENCES brewing_method (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recipes_user (table: recipe)
ALTER TABLE recipe ADD CONSTRAINT recipes_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recipes_coffee (table: recipe)
ALTER TABLE recipe ADD CONSTRAINT recipes_coffee
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recommendations_coffee (table: recommendations)
ALTER TABLE recommendations ADD CONSTRAINT recommendations_coffee
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recommendations_ranking_coffee (table: recommendations)
ALTER TABLE recommendations ADD CONSTRAINT recommendations_ranking_coffee
    FOREIGN KEY (coffee_ranking_id)
        REFERENCES coffee_ranking (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recommendations_recipe (table: recommendations)
ALTER TABLE recommendations ADD CONSTRAINT recommendations_recipe
    FOREIGN KEY (recipe_id)
        REFERENCES recipe (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recommendations_user (table: recommendations)
ALTER TABLE recommendations ADD CONSTRAINT recommendations_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: recommendations_user_preferences (table: recommendations)
ALTER TABLE recommendations ADD CONSTRAINT recommendations_user_preferences
    FOREIGN KEY (user_preference_id)
        REFERENCES user_preference (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: region_country (table: region)
ALTER TABLE region ADD CONSTRAINT region_country
    FOREIGN KEY (country_id)
        REFERENCES country (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: user_preferences_user (table: user_preference)
ALTER TABLE user_preference ADD CONSTRAINT user_preferences_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: user_recipe_favorite_user (table: user_recipe_favorite)
ALTER TABLE user_recipe_favorite ADD CONSTRAINT user_recipe_favorite_user
    FOREIGN KEY (user_id)
        REFERENCES app_user (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;

-- Reference: user_recipe_favorite_recipe (table: user_recipe_favorite)
ALTER TABLE user_recipe_favorite ADD CONSTRAINT user_recipe_favorite_recipe
    FOREIGN KEY (recipe_id)
        REFERENCES recipe (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE
;


-- =====================
-- CHECK Constraints
-- =====================
ALTER TABLE recommendations ADD CONSTRAINT chk_recommendation_target
    CHECK ( (coffee_id IS NOT NULL AND recipe_id IS NULL) OR (coffee_id IS NULL AND recipe_id IS NOT NULL)
        );

-- coffee_rating: zakres oceny 1-5
ALTER TABLE coffee_rating ADD CONSTRAINT chk_coffee_rating_value
    CHECK (value BETWEEN 1 AND 5);

-- recipe_rating: zakres oceny 1-5
ALTER TABLE recipe_rating ADD CONSTRAINT chk_recipe_rating_value
    CHECK (value BETWEEN 1 AND 5);

-- =====================
-- INDEXES (ALL FOREIGN KEYS)
-- =====================

-- article
CREATE INDEX idx_article_user_id ON article(user_id);
CREATE INDEX idx_article_moderated_by_user_id ON article(moderated_by_user_id);

-- coffee
CREATE INDEX idx_coffee_created_by_user_id ON coffee(created_by_user_id);
CREATE INDEX idx_coffee_region_id ON coffee(region_id);
CREATE INDEX idx_coffee_roastery_id ON coffee(roastery_id);
CREATE INDEX idx_coffee_processing_method_id ON coffee(processing_method_id);
CREATE INDEX idx_coffee_variety_id ON coffee(variety_id);
CREATE INDEX idx_coffee_cupping_session_id ON coffee(cupping_session_id);

-- coffee_rating
CREATE INDEX idx_coffee_rating_user_id ON coffee_rating(user_id);
CREATE INDEX idx_coffee_rating_coffee_id ON coffee_rating(coffee_id);

-- coffee_ranking
CREATE INDEX idx_coffee_ranking_coffee_id ON coffee_ranking(coffee_id);

-- recipe
CREATE INDEX idx_recipe_user_id ON recipe(user_id);
CREATE INDEX idx_recipe_coffee_id ON recipe(coffee_id);
CREATE INDEX idx_recipe_brewing_method_id ON recipe(brewing_method_id);

-- recipe_rating
CREATE INDEX idx_recipe_rating_user_id ON recipe_rating(user_id);
CREATE INDEX idx_recipe_rating_recipe_id ON recipe_rating(recipe_id);

-- recipe_ranking
CREATE INDEX idx_recipe_ranking_recipe_id ON recipe_ranking(recipe_id);

-- recommendations
CREATE INDEX idx_recommendations_user_id ON recommendations(user_id);
CREATE INDEX idx_recommendations_coffee_id ON recommendations(coffee_id);
CREATE INDEX idx_recommendations_recipe_id ON recommendations(recipe_id);
CREATE INDEX idx_recommendations_user_preference_id ON recommendations(user_preference_id);
CREATE INDEX idx_recommendations_coffee_ranking_id ON recommendations(coffee_ranking_id);

-- user_preference
CREATE INDEX idx_user_preference_user_id ON user_preference(user_id);

-- user_ranking
CREATE INDEX idx_user_ranking_user_id ON user_ranking(user_id);

-- user_recipe_favorite
CREATE INDEX idx_user_recipe_favorite_recipe_id ON user_recipe_favorite(recipe_id);

-- cupping_session
CREATE INDEX idx_cupping_session_user_id ON cupping_session(user_id);

-- notification
CREATE INDEX idx_notification_user_id ON notification(user_id);

-- quick_note
CREATE INDEX idx_quick_note_user_id ON quick_note(user_id);

-- region
CREATE INDEX idx_region_country_id ON region(country_id);

-- follow
CREATE INDEX idx_follow_followed_id ON follow(followed_id);