export const COFFEE_REGIONS = [
    "Yirgacheffe",
    "Sidamo",
    "Guji",
    "Harrar",
    "Huila",
    "Nariño",
    "Cauca",
    "Antioquia",
    "Nyeri",
    "Kirinyaga",
    "Nakuru",
    "Tarrazu",
    "West Valley",
    "Aceh",
    "Sumatra",
    "Sulawesi",
    "Blue Mountain",
    "Minas Gerais",
    "Boquete",
    "Kivu",
];
