export const COFFEE_FLAVOR_PROFILES = [
    "Jaśmin",
    "Cytrusy",
    "Bergamotka",
    "Miód",
    "Czekolada",
    "Karmel",
    "Orzechy",
    "Czerwone owoce",
    "Jagody",
    "Winne",
    "Kwiaty",
    "Herbaciane",
    "Przyprawy",
    "Tropikalne owoce",
    "Porzeczka",
    "Brzoskwinia",
    "Jabłko",
];
