CREATE TABLE report (
                        id int GENERATED BY DEFAULT AS IDENTITY,
                        reason text NOT NULL,
                        created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        article_id int NOT NULL,
                        reported_by_user_id int NOT NULL,

                        CONSTRAINT report_pk PRIMARY KEY (id),

                        CONSTRAINT report_article_fk
                            FOREIGN KEY (article_id)
                                REFERENCES article(id),

                        CONSTRAINT report_user_fk
                            FOREIGN KEY (reported_by_user_id)
                                REFERENCES app_user(id)
);

CREATE INDEX idx_report_article_id
    ON report(article_id);

CREATE INDEX idx_report_reported_by_user_id
    ON report(reported_by_user_id);