BEGIN;

CREATE TABLE IF NOT EXISTS acidity (
                                       id int GENERATED BY DEFAULT AS IDENTITY,
                                       name varchar(255) NOT NULL,
    description text NULL,
    CONSTRAINT acidity_pk PRIMARY KEY (id),
    CONSTRAINT acidity_name_key UNIQUE (name)
    );

CREATE TABLE IF NOT EXISTS body (
                                    id int GENERATED BY DEFAULT AS IDENTITY,
                                    name varchar(255) NOT NULL,
    description text NULL,
    CONSTRAINT body_pk PRIMARY KEY (id),
    CONSTRAINT body_name_key UNIQUE (name)
    );

INSERT INTO acidity (name, description)
VALUES
    ('Low', 'Delikatna, niska kwasowość.'),
    ('Medium', 'Zbalansowana, średnia kwasowość.'),
    ('High', 'Wyraźna, żywa kwasowość.')
    ON CONFLICT (name) DO NOTHING;

INSERT INTO body (name, description)
VALUES
    ('Light', 'Lekkie body, delikatna tekstura.'),
    ('Balanced', 'Zbalansowane body.'),
    ('Heavy', 'Pełne, cięższe body.')
    ON CONFLICT (name) DO NOTHING;

ALTER TABLE coffee
    ADD COLUMN IF NOT EXISTS acidity_id int NULL;

ALTER TABLE coffee
    ADD COLUMN IF NOT EXISTS body_id int NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'coffee_acidity'
    ) THEN
ALTER TABLE coffee
    ADD CONSTRAINT coffee_acidity
        FOREIGN KEY (acidity_id)
            REFERENCES acidity(id);
END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'coffee_body'
    ) THEN
ALTER TABLE coffee
    ADD CONSTRAINT coffee_body
        FOREIGN KEY (body_id)
            REFERENCES body(id);
END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_coffee_acidity_id ON coffee(acidity_id);
CREATE INDEX IF NOT EXISTS idx_coffee_body_id ON coffee(body_id);

UPDATE coffee
SET acidity_id = (SELECT id FROM acidity WHERE name = 'Medium')
WHERE acidity_id IS NULL;

UPDATE coffee
SET body_id = (SELECT id FROM body WHERE name = 'Balanced')
WHERE body_id IS NULL;

COMMIT;