ALTER TABLE cupping_session
    RENAME COLUMN notes TO description;

ALTER TABLE cupping_session
    ALTER COLUMN description DROP NOT NULL;

ALTER TABLE cupping_session
    ADD COLUMN created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE cupping_session_coffee (
                                        id int GENERATED BY DEFAULT AS IDENTITY,
                                        notes text NULL,
                                        created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        coffee_id int NOT NULL,
                                        cupping_session_id int NOT NULL,
                                        CONSTRAINT cupping_session_coffee_pk PRIMARY KEY (id),
                                        CONSTRAINT uq_session_coffee UNIQUE (cupping_session_id, coffee_id)
);

ALTER TABLE cupping_session_coffee ADD CONSTRAINT cupping_session_coffee_coffee
    FOREIGN KEY (coffee_id)
        REFERENCES coffee (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE;

ALTER TABLE cupping_session_coffee ADD CONSTRAINT cupping_session_coffee_session
    FOREIGN KEY (cupping_session_id)
        REFERENCES cupping_session (id)
        NOT DEFERRABLE
            INITIALLY IMMEDIATE;

INSERT INTO cupping_session_coffee (
    coffee_id,
    cupping_session_id,
    created_at
)
SELECT
    id,
    cupping_session_id,
    CURRENT_TIMESTAMP
FROM coffee
WHERE cupping_session_id IS NOT NULL;

ALTER TABLE coffee DROP CONSTRAINT IF EXISTS coffee_cupping_session;

DROP INDEX IF EXISTS idx_coffee_cupping_session_id;

ALTER TABLE coffee DROP COLUMN IF EXISTS cupping_session_id;

CREATE INDEX idx_cupping_session_coffee_coffee_id
    ON cupping_session_coffee(coffee_id);

CREATE INDEX idx_cupping_session_coffee_cupping_session_id
    ON cupping_session_coffee(cupping_session_id);
